# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('questionid', models.CharField(max_length=100)),
                ('answername', models.CharField(max_length=100)),
                ('likenum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerid', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionname', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=300)),
                ('questioner', models.CharField(max_length=100)),
                ('answernum', models.IntegerField()),
                ('remind', models.IntegerField()),
            ],
        ),
    ]
